////////////////////////////////////////
//native interaction
var UI=exports;

Duktape.__ui_native_hack(UI);

UI.IS_MOBILE=(UI.Platform.ARCH=="android"||UI.Platform.ARCH=="ios");
UI.IS_APPLE=(UI.Platform.ARCH=="mac"||UI.Platform.ARCH=="ios");
if(UI.Platform.BUILD=="debug"){
	UI.assert=function(cond,message){
		if(!cond){
			throw new Error(message)
		}
	}
}else{
	UI.assert=function(){}
}

UI.SDL_ICONV_ERROR=-1
UI.SDL_ICONV_E2BIG=-2
UI.SDL_ICONV_EILSEQ=-3
UI.SDL_ICONV_EINVAL=-4
UI.KMOD_CAPS=8192
UI.KMOD_LALT=256
UI.KMOD_LCTRL=64
UI.KMOD_LGUI=1024
UI.KMOD_LWIN=1024
UI.KMOD_LSHIFT=1
UI.KMOD_MODE=16384
UI.KMOD_NONE=0
UI.KMOD_NUM=4096
UI.KMOD_RALT=512
UI.KMOD_RCTRL=128
UI.KMOD_RESERVED=32768
UI.KMOD_RGUI=2048
UI.KMOD_RWIN=2048
UI.KMOD_RSHIFT=2
UI.SDLK_0=48
UI.SDLK_1=49
UI.SDLK_2=50
UI.SDLK_3=51
UI.SDLK_4=52
UI.SDLK_5=53
UI.SDLK_6=54
UI.SDLK_7=55
UI.SDLK_8=56
UI.SDLK_9=57
UI.SDLK_AC_BACK=1073742094
UI.SDLK_AC_BOOKMARKS=1073742098
UI.SDLK_AC_FORWARD=1073742095
UI.SDLK_AC_HOME=1073742093
UI.SDLK_AC_REFRESH=1073742097
UI.SDLK_AC_SEARCH=1073742092
UI.SDLK_AC_STOP=1073742096
UI.SDLK_AGAIN=1073741945
UI.SDLK_ALTERASE=1073741977
UI.SDLK_AMPERSAND=38
UI.SDLK_APPLICATION=1073741925
UI.SDLK_ASTERISK=42
UI.SDLK_AT=64
UI.SDLK_AUDIOMUTE=1073742086
UI.SDLK_AUDIONEXT=1073742082
UI.SDLK_AUDIOPLAY=1073742085
UI.SDLK_AUDIOPREV=1073742083
UI.SDLK_AUDIOSTOP=1073742084
UI.SDLK_BACKQUOTE=96
UI.SDLK_BACKSLASH=92
UI.SDLK_BACKSPACE=8
UI.SDLK_BRIGHTNESSDOWN=1073742099
UI.SDLK_BRIGHTNESSUP=1073742100
UI.SDLK_CALCULATOR=1073742090
UI.SDLK_CANCEL=1073741979
UI.SDLK_CAPSLOCK=1073741881
UI.SDLK_CARET=94
UI.SDLK_CLEAR=1073741980
UI.SDLK_CLEARAGAIN=1073741986
UI.SDLK_COLON=58
UI.SDLK_COMMA=44
UI.SDLK_COMPUTER=1073742091
UI.SDLK_COPY=1073741948
UI.SDLK_CRSEL=1073741987
UI.SDLK_CURRENCYSUBUNIT=1073742005
UI.SDLK_CURRENCYUNIT=1073742004
UI.SDLK_CUT=1073741947
UI.SDLK_DECIMALSEPARATOR=1073742003
UI.SDLK_DELETE=127
UI.SDLK_DISPLAYSWITCH=1073742101
UI.SDLK_DOLLAR=36
UI.SDLK_DOWN=1073741905
UI.SDLK_EJECT=1073742105
UI.SDLK_END=1073741901
UI.SDLK_EQUALS=61
UI.SDLK_ESCAPE=27
UI.SDLK_EXCLAIM=33
UI.SDLK_EXECUTE=1073741940
UI.SDLK_EXSEL=1073741988
UI.SDLK_F1=1073741882
UI.SDLK_F10=1073741891
UI.SDLK_F11=1073741892
UI.SDLK_F12=1073741893
UI.SDLK_F13=1073741928
UI.SDLK_F14=1073741929
UI.SDLK_F15=1073741930
UI.SDLK_F16=1073741931
UI.SDLK_F17=1073741932
UI.SDLK_F18=1073741933
UI.SDLK_F19=1073741934
UI.SDLK_F2=1073741883
UI.SDLK_F20=1073741935
UI.SDLK_F21=1073741936
UI.SDLK_F22=1073741937
UI.SDLK_F23=1073741938
UI.SDLK_F24=1073741939
UI.SDLK_F3=1073741884
UI.SDLK_F4=1073741885
UI.SDLK_F5=1073741886
UI.SDLK_F6=1073741887
UI.SDLK_F7=1073741888
UI.SDLK_F8=1073741889
UI.SDLK_F9=1073741890
UI.SDLK_FIND=1073741950
UI.SDLK_GREATER=62
UI.SDLK_HASH=35
UI.SDLK_HELP=1073741941
UI.SDLK_HOME=1073741898
UI.SDLK_INSERT=1073741897
UI.SDLK_KBDILLUMDOWN=1073742103
UI.SDLK_KBDILLUMTOGGLE=1073742102
UI.SDLK_KBDILLUMUP=1073742104
UI.SDLK_KP_0=1073741922
UI.SDLK_KP_00=1073742000
UI.SDLK_KP_000=1073742001
UI.SDLK_KP_1=1073741913
UI.SDLK_KP_2=1073741914
UI.SDLK_KP_3=1073741915
UI.SDLK_KP_4=1073741916
UI.SDLK_KP_5=1073741917
UI.SDLK_KP_6=1073741918
UI.SDLK_KP_7=1073741919
UI.SDLK_KP_8=1073741920
UI.SDLK_KP_9=1073741921
UI.SDLK_KP_A=1073742012
UI.SDLK_KP_AMPERSAND=1073742023
UI.SDLK_KP_AT=1073742030
UI.SDLK_KP_B=1073742013
UI.SDLK_KP_BACKSPACE=1073742011
UI.SDLK_KP_BINARY=1073742042
UI.SDLK_KP_C=1073742014
UI.SDLK_KP_CLEAR=1073742040
UI.SDLK_KP_CLEARENTRY=1073742041
UI.SDLK_KP_COLON=1073742027
UI.SDLK_KP_COMMA=1073741957
UI.SDLK_KP_D=1073742015
UI.SDLK_KP_DBLAMPERSAND=1073742024
UI.SDLK_KP_DBLVERTICALBAR=1073742026
UI.SDLK_KP_DECIMAL=1073742044
UI.SDLK_KP_DIVIDE=1073741908
UI.SDLK_KP_E=1073742016
UI.SDLK_KP_ENTER=1073741912
UI.SDLK_KP_EQUALS=1073741927
UI.SDLK_KP_EQUALSAS400=1073741958
UI.SDLK_KP_EXCLAM=1073742031
UI.SDLK_KP_F=1073742017
UI.SDLK_KP_GREATER=1073742022
UI.SDLK_KP_HASH=1073742028
UI.SDLK_KP_HEXADECIMAL=1073742045
UI.SDLK_KP_LEFTBRACE=1073742008
UI.SDLK_KP_LEFTPAREN=1073742006
UI.SDLK_KP_LESS=1073742021
UI.SDLK_KP_MEMADD=1073742035
UI.SDLK_KP_MEMCLEAR=1073742034
UI.SDLK_KP_MEMDIVIDE=1073742038
UI.SDLK_KP_MEMMULTIPLY=1073742037
UI.SDLK_KP_MEMRECALL=1073742033
UI.SDLK_KP_MEMSTORE=1073742032
UI.SDLK_KP_MEMSUBTRACT=1073742036
UI.SDLK_KP_MINUS=1073741910
UI.SDLK_KP_MULTIPLY=1073741909
UI.SDLK_KP_OCTAL=1073742043
UI.SDLK_KP_PERCENT=1073742020
UI.SDLK_KP_PERIOD=1073741923
UI.SDLK_KP_PLUS=1073741911
UI.SDLK_KP_PLUSMINUS=1073742039
UI.SDLK_KP_POWER=1073742019
UI.SDLK_KP_RIGHTBRACE=1073742009
UI.SDLK_KP_RIGHTPAREN=1073742007
UI.SDLK_KP_SPACE=1073742029
UI.SDLK_KP_TAB=1073742010
UI.SDLK_KP_VERTICALBAR=1073742025
UI.SDLK_KP_XOR=1073742018
UI.SDLK_LALT=1073742050
UI.SDLK_LCTRL=1073742048
UI.SDLK_LEFT=1073741904
UI.SDLK_LEFTBRACKET=91
UI.SDLK_LEFTPAREN=40
UI.SDLK_LESS=60
UI.SDLK_LGUI=1073742051
UI.SDLK_LSHIFT=1073742049
UI.SDLK_MAIL=1073742089
UI.SDLK_MEDIASELECT=1073742087
UI.SDLK_MENU=1073741942
UI.SDLK_MINUS=45
UI.SDLK_MODE=1073742081
UI.SDLK_MUTE=1073741951
UI.SDLK_NUMLOCKCLEAR=1073741907
UI.SDLK_OPER=1073741985
UI.SDLK_OUT=1073741984
UI.SDLK_PAGEDOWN=1073741902
UI.SDLK_PAGEUP=1073741899
UI.SDLK_PASTE=1073741949
UI.SDLK_PAUSE=1073741896
UI.SDLK_PERCENT=37
UI.SDLK_PERIOD=46
UI.SDLK_PLUS=43
UI.SDLK_POWER=1073741926
UI.SDLK_PRINTSCREEN=1073741894
UI.SDLK_PRIOR=1073741981
UI.SDLK_QUESTION=63
UI.SDLK_QUOTE=39
UI.SDLK_QUOTEDBL=34
UI.SDLK_RALT=1073742054
UI.SDLK_RCTRL=1073742052
UI.SDLK_RETURN=13
UI.SDLK_RETURN2=1073741982
UI.SDLK_RGUI=1073742055
UI.SDLK_RIGHT=1073741903
UI.SDLK_RIGHTBRACKET=93
UI.SDLK_RIGHTPAREN=41
UI.SDLK_RSHIFT=1073742053
UI.SDLK_SCROLLLOCK=1073741895
UI.SDLK_SELECT=1073741943
UI.SDLK_SEMICOLON=59
UI.SDLK_SEPARATOR=1073741983
UI.SDLK_SLASH=47
UI.SDLK_SLEEP=1073742106
UI.SDLK_SPACE=32
UI.SDLK_STOP=1073741944
UI.SDLK_SYSREQ=1073741978
UI.SDLK_TAB=9
UI.SDLK_THOUSANDSSEPARATOR=1073742002
UI.SDLK_UNDERSCORE=95
UI.SDLK_UNDO=1073741946
UI.SDLK_UNKNOWN=0
UI.SDLK_UP=1073741906
UI.SDLK_VOLUMEDOWN=1073741953
UI.SDLK_VOLUMEUP=1073741952
UI.SDLK_WWW=1073742088
UI.SDLK_a=97
UI.SDLK_b=98
UI.SDLK_c=99
UI.SDLK_d=100
UI.SDLK_e=101
UI.SDLK_f=102
UI.SDLK_g=103
UI.SDLK_h=104
UI.SDLK_i=105
UI.SDLK_j=106
UI.SDLK_k=107
UI.SDLK_l=108
UI.SDLK_m=109
UI.SDLK_n=110
UI.SDLK_o=111
UI.SDLK_p=112
UI.SDLK_q=113
UI.SDLK_r=114
UI.SDLK_s=115
UI.SDLK_t=116
UI.SDLK_u=117
UI.SDLK_v=118
UI.SDLK_w=119
UI.SDLK_x=120
UI.SDLK_y=121
UI.SDLK_z=122
UI.SDL_ADDEVENT=0
UI.SDL_ALPHA_OPAQUE=255
UI.SDL_ALPHA_TRANSPARENT=0
UI.SDL_ANDROID_EXTERNAL_STORAGE_READ=1
UI.SDL_ANDROID_EXTERNAL_STORAGE_WRITE=2
UI.SDL_APP_DIDENTERBACKGROUND=260
UI.SDL_APP_DIDENTERFOREGROUND=262
UI.SDL_APP_LOWMEMORY=258
UI.SDL_APP_TERMINATING=257
UI.SDL_APP_WILLENTERBACKGROUND=259
UI.SDL_APP_WILLENTERFOREGROUND=261
UI.SDL_ARRAYORDER_ABGR=6
UI.SDL_ARRAYORDER_ARGB=3
UI.SDL_ARRAYORDER_BGR=4
UI.SDL_ARRAYORDER_BGRA=5
UI.SDL_ARRAYORDER_NONE=0
UI.SDL_ARRAYORDER_RGB=1
UI.SDL_ARRAYORDER_RGBA=2
UI.SDL_ASSEMBLY_ROUTINES=1
UI.SDL_ASSERTION_ABORT=2
UI.SDL_ASSERTION_ALWAYS_IGNORE=4
UI.SDL_ASSERTION_BREAK=1
UI.SDL_ASSERTION_IGNORE=3
UI.SDL_ASSERTION_RETRY=0
UI.SDL_ASSERT_LEVEL=2
UI.SDL_AUDIO_ALLOW_CHANNELS_CHANGE=4
UI.SDL_AUDIO_ALLOW_FORMAT_CHANGE=2
UI.SDL_AUDIO_ALLOW_FREQUENCY_CHANGE=1
UI.SDL_AUDIO_DRIVER_DISK=1
UI.SDL_AUDIO_DRIVER_DSOUND=1
UI.SDL_AUDIO_DRIVER_DUMMY=1
UI.SDL_AUDIO_DRIVER_WINMM=1
UI.SDL_AUDIO_DRIVER_XAUDIO2=1
UI.SDL_AUDIO_PAUSED=2
UI.SDL_AUDIO_PLAYING=1
UI.SDL_AUDIO_STOPPED=0
UI.SDL_BIG_ENDIAN=4321
UI.SDL_BITMAPORDER_1234=2
UI.SDL_BITMAPORDER_4321=1
UI.SDL_BITMAPORDER_NONE=0
UI.SDL_BLENDMODE_ADD=2
UI.SDL_BLENDMODE_BLEND=1
UI.SDL_BLENDMODE_MOD=4
UI.SDL_BLENDMODE_NONE=0
UI.SDL_BUTTON_LEFT=1
UI.SDL_BUTTON_LMASK=1
UI.SDL_BUTTON_MIDDLE=2
UI.SDL_BUTTON_MMASK=2
UI.SDL_BUTTON_RIGHT=3
UI.SDL_BUTTON_RMASK=4
UI.SDL_BUTTON_X1=4
UI.SDL_BUTTON_X1MASK=8
UI.SDL_BUTTON_X2=5
UI.SDL_BUTTON_X2MASK=16
UI.SDL_BYTEORDER=1234
UI.SDL_CACHELINE_SIZE=128
UI.SDL_CLIPBOARDUPDATE=2304
UI.SDL_COMPILEDVERSION=2003
UI.SDL_CONTROLLERAXISMOTION=1616
UI.SDL_CONTROLLERBUTTONDOWN=1617
UI.SDL_CONTROLLERBUTTONUP=1618
UI.SDL_CONTROLLERDEVICEADDED=1619
UI.SDL_CONTROLLERDEVICEREMAPPED=1621
UI.SDL_CONTROLLERDEVICEREMOVED=1620
UI.SDL_CONTROLLER_AXIS_INVALID=-1
UI.SDL_CONTROLLER_AXIS_LEFTX=0
UI.SDL_CONTROLLER_AXIS_LEFTY=1
UI.SDL_CONTROLLER_AXIS_MAX=6
UI.SDL_CONTROLLER_AXIS_RIGHTX=2
UI.SDL_CONTROLLER_AXIS_RIGHTY=3
UI.SDL_CONTROLLER_AXIS_TRIGGERLEFT=4
UI.SDL_CONTROLLER_AXIS_TRIGGERRIGHT=5
UI.SDL_CONTROLLER_BINDTYPE_AXIS=2
UI.SDL_CONTROLLER_BINDTYPE_BUTTON=1
UI.SDL_CONTROLLER_BINDTYPE_HAT=3
UI.SDL_CONTROLLER_BINDTYPE_NONE=0
UI.SDL_CONTROLLER_BUTTON_A=0
UI.SDL_CONTROLLER_BUTTON_B=1
UI.SDL_CONTROLLER_BUTTON_BACK=4
UI.SDL_CONTROLLER_BUTTON_DPAD_DOWN=12
UI.SDL_CONTROLLER_BUTTON_DPAD_LEFT=13
UI.SDL_CONTROLLER_BUTTON_DPAD_RIGHT=14
UI.SDL_CONTROLLER_BUTTON_DPAD_UP=11
UI.SDL_CONTROLLER_BUTTON_GUIDE=5
UI.SDL_CONTROLLER_BUTTON_INVALID=-1
UI.SDL_CONTROLLER_BUTTON_LEFTSHOULDER=9
UI.SDL_CONTROLLER_BUTTON_LEFTSTICK=7
UI.SDL_CONTROLLER_BUTTON_MAX=15
UI.SDL_CONTROLLER_BUTTON_RIGHTSHOULDER=10
UI.SDL_CONTROLLER_BUTTON_RIGHTSTICK=8
UI.SDL_CONTROLLER_BUTTON_START=6
UI.SDL_CONTROLLER_BUTTON_X=2
UI.SDL_CONTROLLER_BUTTON_Y=3
UI.SDL_DISABLE=0
UI.SDL_DOLLARGESTURE=2048
UI.SDL_DOLLARRECORD=2049
UI.SDL_DONTFREE=4
UI.SDL_DROPFILE=4096
UI.SDL_EFREAD=1
UI.SDL_EFSEEK=3
UI.SDL_EFWRITE=2
UI.SDL_ENABLE=1
UI.SDL_ENOMEM=0
UI.SDL_FALSE=0
UI.SDL_FILESYSTEM_WINDOWS=1
UI.SDL_FINGERDOWN=1792
UI.SDL_FINGERMOTION=1794
UI.SDL_FINGERUP=1793
UI.SDL_FIRSTEVENT=0
UI.SDL_FLIP_HORIZONTAL=1
UI.SDL_FLIP_NONE=0
UI.SDL_FLIP_VERTICAL=2
UI.SDL_GETEVENT=2
UI.SDL_GL_ACCELERATED_VISUAL=15
UI.SDL_GL_ACCUM_ALPHA_SIZE=11
UI.SDL_GL_ACCUM_BLUE_SIZE=10
UI.SDL_GL_ACCUM_GREEN_SIZE=9
UI.SDL_GL_ACCUM_RED_SIZE=8
UI.SDL_GL_ALPHA_SIZE=3
UI.SDL_GL_BLUE_SIZE=2
UI.SDL_GL_BUFFER_SIZE=4
UI.SDL_GL_CONTEXT_DEBUG_FLAG=1
UI.SDL_GL_CONTEXT_EGL=19
UI.SDL_GL_CONTEXT_FLAGS=20
UI.SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG=2
UI.SDL_GL_CONTEXT_MAJOR_VERSION=17
UI.SDL_GL_CONTEXT_MINOR_VERSION=18
UI.SDL_GL_CONTEXT_PROFILE_COMPATIBILITY=2
UI.SDL_GL_CONTEXT_PROFILE_CORE=1
UI.SDL_GL_CONTEXT_PROFILE_ES=4
UI.SDL_GL_CONTEXT_PROFILE_MASK=21
UI.SDL_GL_CONTEXT_RESET_ISOLATION_FLAG=8
UI.SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG=4
UI.SDL_GL_DEPTH_SIZE=6
UI.SDL_GL_DOUBLEBUFFER=5
UI.SDL_GL_FRAMEBUFFER_SRGB_CAPABLE=23
UI.SDL_GL_GREEN_SIZE=1
UI.SDL_GL_MULTISAMPLEBUFFERS=13
UI.SDL_GL_MULTISAMPLESAMPLES=14
UI.SDL_GL_RED_SIZE=0
UI.SDL_GL_RETAINED_BACKING=16
UI.SDL_GL_SHARE_WITH_CURRENT_CONTEXT=22
UI.SDL_GL_STENCIL_SIZE=7
UI.SDL_GL_STEREO=12
UI.SDL_HAPTIC_CARTESIAN=1
UI.SDL_HAPTIC_DINPUT=1
UI.SDL_HAPTIC_INFINITY=-1
UI.SDL_HAPTIC_POLAR=0
UI.SDL_HAPTIC_SPHERICAL=2
UI.SDL_HAT_CENTERED=0
UI.SDL_HAT_DOWN=4
UI.SDL_HAT_LEFT=8
UI.SDL_HAT_RIGHT=2
UI.SDL_HAT_UP=1
UI.SDL_HINT_ACCELEROMETER_AS_JOYSTICK="SDL_ACCELEROMETER_AS_JOYSTICK"
UI.SDL_HINT_ALLOW_TOPMOST="SDL_ALLOW_TOPMOST"
UI.SDL_HINT_DEFAULT=null
UI.SDL_HINT_FRAMEBUFFER_ACCELERATION="SDL_FRAMEBUFFER_ACCELERATION"
UI.SDL_HINT_GAMECONTROLLERCONFIG="SDL_GAMECONTROLLERCONFIG"
UI.SDL_HINT_GRAB_KEYBOARD="SDL_GRAB_KEYBOARD"
UI.SDL_HINT_IDLE_TIMER_DISABLED="SDL_IOS_IDLE_TIMER_DISABLED"
UI.SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS="SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS"
UI.SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK="SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK"
UI.SDL_HINT_MOUSE_RELATIVE_MODE_WARP="SDL_MOUSE_RELATIVE_MODE_WARP"
UI.SDL_HINT_NORMAL=1
UI.SDL_HINT_ORIENTATIONS="SDL_IOS_ORIENTATIONS"
UI.SDL_HINT_OVERRIDE=2
UI.SDL_HINT_RENDER_DIRECT3D11_DEBUG="SDL_HINT_RENDER_DIRECT3D11_DEBUG"
UI.SDL_HINT_RENDER_DIRECT3D_THREADSAFE="SDL_RENDER_DIRECT3D_THREADSAFE"
UI.SDL_HINT_RENDER_DRIVER="SDL_RENDER_DRIVER"
UI.SDL_HINT_RENDER_OPENGL_SHADERS="SDL_RENDER_OPENGL_SHADERS"
UI.SDL_HINT_RENDER_SCALE_QUALITY="SDL_RENDER_SCALE_QUALITY"
UI.SDL_HINT_RENDER_VSYNC="SDL_RENDER_VSYNC"
UI.SDL_HINT_TIMER_RESOLUTION="SDL_TIMER_RESOLUTION"
UI.SDL_HINT_VIDEO_ALLOW_SCREENSAVER="SDL_VIDEO_ALLOW_SCREENSAVER"
UI.SDL_HINT_VIDEO_HIGHDPI_DISABLED="SDL_VIDEO_HIGHDPI_DISABLED"
UI.SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES="SDL_VIDEO_MAC_FULLSCREEN_SPACES"
UI.SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS="SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS"
UI.SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT="SDL_VIDEO_WINDOW_SHARE_PIXEL_FORMAT"
UI.SDL_HINT_VIDEO_WIN_D3DCOMPILER="SDL_VIDEO_WIN_D3DCOMPILER"
UI.SDL_HINT_VIDEO_X11_XINERAMA="SDL_VIDEO_X11_XINERAMA"
UI.SDL_HINT_VIDEO_X11_XRANDR="SDL_VIDEO_X11_XRANDR"
UI.SDL_HINT_VIDEO_X11_XVIDMODE="SDL_VIDEO_X11_XVIDMODE"
UI.SDL_HINT_XINPUT_ENABLED="SDL_XINPUT_ENABLED"
UI.SDL_IGNORE=0
UI.SDL_INIT_AUDIO=16
UI.SDL_INIT_EVENTS=16384
UI.SDL_INIT_GAMECONTROLLER=8192
UI.SDL_INIT_HAPTIC=4096
UI.SDL_INIT_JOYSTICK=512
UI.SDL_INIT_NOPARACHUTE=1048576
UI.SDL_INIT_TIMER=1
UI.SDL_INIT_VIDEO=32
UI.SDL_JOYAXISMOTION=1536
UI.SDL_JOYBALLMOTION=1537
UI.SDL_JOYBUTTONDOWN=1539
UI.SDL_JOYBUTTONUP=1540
UI.SDL_JOYDEVICEADDED=1541
UI.SDL_JOYDEVICEREMOVED=1542
UI.SDL_JOYHATMOTION=1538
UI.SDL_JOYSTICK_DINPUT=1
UI.SDL_KEYDOWN=768
UI.SDL_KEYUP=769
UI.SDL_LASTERROR=5
UI.SDL_LASTEVENT=65535
UI.SDL_LIL_ENDIAN=1234
UI.SDL_LINE=461
UI.SDL_LOADSO_WINDOWS=1
UI.SDL_LOG_CATEGORY_APPLICATION=0
UI.SDL_LOG_CATEGORY_ASSERT=2
UI.SDL_LOG_CATEGORY_AUDIO=4
UI.SDL_LOG_CATEGORY_CUSTOM=19
UI.SDL_LOG_CATEGORY_ERROR=1
UI.SDL_LOG_CATEGORY_INPUT=7
UI.SDL_LOG_CATEGORY_RENDER=6
UI.SDL_LOG_CATEGORY_RESERVED1=9
UI.SDL_LOG_CATEGORY_RESERVED10=18
UI.SDL_LOG_CATEGORY_RESERVED2=10
UI.SDL_LOG_CATEGORY_RESERVED3=11
UI.SDL_LOG_CATEGORY_RESERVED4=12
UI.SDL_LOG_CATEGORY_RESERVED5=13
UI.SDL_LOG_CATEGORY_RESERVED6=14
UI.SDL_LOG_CATEGORY_RESERVED7=15
UI.SDL_LOG_CATEGORY_RESERVED8=16
UI.SDL_LOG_CATEGORY_RESERVED9=17
UI.SDL_LOG_CATEGORY_SYSTEM=3
UI.SDL_LOG_CATEGORY_TEST=8
UI.SDL_LOG_CATEGORY_VIDEO=5
UI.SDL_LOG_PRIORITY_CRITICAL=6
UI.SDL_LOG_PRIORITY_DEBUG=2
UI.SDL_LOG_PRIORITY_ERROR=5
UI.SDL_LOG_PRIORITY_INFO=3
UI.SDL_LOG_PRIORITY_VERBOSE=1
UI.SDL_LOG_PRIORITY_WARN=4
UI.SDL_MAJOR_VERSION=2
UI.SDL_MAX_LOG_MESSAGE=4096
UI.SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT=2
UI.SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT=1
UI.SDL_MESSAGEBOX_COLOR_BACKGROUND=0
UI.SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND=3
UI.SDL_MESSAGEBOX_COLOR_BUTTON_BORDER=2
UI.SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED=4
UI.SDL_MESSAGEBOX_COLOR_MAX=5
UI.SDL_MESSAGEBOX_COLOR_TEXT=1
UI.SDL_MESSAGEBOX_ERROR=16
UI.SDL_MESSAGEBOX_INFORMATION=64
UI.SDL_MESSAGEBOX_WARNING=32
UI.SDL_MINOR_VERSION=0
UI.SDL_MIX_MAXVOLUME=128
UI.SDL_MOUSEBUTTONDOWN=1025
UI.SDL_MOUSEBUTTONUP=1026
UI.SDL_MOUSEMOTION=1024
UI.SDL_MOUSEWHEEL=1027
UI.SDL_MULTIGESTURE=2050
UI.SDL_MUTEX_TIMEDOUT=1
UI.SDL_NUM_LOG_PRIORITIES=7
UI.SDL_NUM_SCANCODES=512
UI.SDL_NUM_SYSTEM_CURSORS=12
UI.SDL_PACKEDLAYOUT_1010102=8
UI.SDL_PACKEDLAYOUT_1555=3
UI.SDL_PACKEDLAYOUT_2101010=7
UI.SDL_PACKEDLAYOUT_332=1
UI.SDL_PACKEDLAYOUT_4444=2
UI.SDL_PACKEDLAYOUT_5551=4
UI.SDL_PACKEDLAYOUT_565=5
UI.SDL_PACKEDLAYOUT_8888=6
UI.SDL_PACKEDLAYOUT_NONE=0
UI.SDL_PACKEDORDER_ABGR=7
UI.SDL_PACKEDORDER_ARGB=3
UI.SDL_PACKEDORDER_BGRA=8
UI.SDL_PACKEDORDER_BGRX=6
UI.SDL_PACKEDORDER_NONE=0
UI.SDL_PACKEDORDER_RGBA=4
UI.SDL_PACKEDORDER_RGBX=2
UI.SDL_PACKEDORDER_XBGR=5
UI.SDL_PACKEDORDER_XRGB=1
UI.SDL_PATCHLEVEL=3
UI.SDL_PEEKEVENT=1
UI.SDL_PIXELFORMAT_ABGR1555=359862274
UI.SDL_PIXELFORMAT_ABGR4444=359796738
UI.SDL_PIXELFORMAT_ABGR8888=376840196
UI.SDL_PIXELFORMAT_ARGB1555=355667970
UI.SDL_PIXELFORMAT_ARGB2101010=372711428
UI.SDL_PIXELFORMAT_ARGB4444=355602434
UI.SDL_PIXELFORMAT_ARGB8888=372645892
UI.SDL_PIXELFORMAT_BGR24=390076419
UI.SDL_PIXELFORMAT_BGR555=357764866
UI.SDL_PIXELFORMAT_BGR565=357896194
UI.SDL_PIXELFORMAT_BGR888=374740996
UI.SDL_PIXELFORMAT_BGRA4444=360845314
UI.SDL_PIXELFORMAT_BGRA5551=360976386
UI.SDL_PIXELFORMAT_BGRA8888=377888772
UI.SDL_PIXELFORMAT_BGRX8888=375789572
UI.SDL_PIXELFORMAT_INDEX1LSB=286261504
UI.SDL_PIXELFORMAT_INDEX1MSB=287310080
UI.SDL_PIXELFORMAT_INDEX4LSB=303039488
UI.SDL_PIXELFORMAT_INDEX4MSB=304088064
UI.SDL_PIXELFORMAT_INDEX8=318769153
UI.SDL_PIXELFORMAT_IYUV=1448433993
UI.SDL_PIXELFORMAT_RGB24=386930691
UI.SDL_PIXELFORMAT_RGB332=336660481
UI.SDL_PIXELFORMAT_RGB444=353504258
UI.SDL_PIXELFORMAT_RGB555=353570562
UI.SDL_PIXELFORMAT_RGB565=353701890
UI.SDL_PIXELFORMAT_RGB888=370546692
UI.SDL_PIXELFORMAT_RGBA4444=356651010
UI.SDL_PIXELFORMAT_RGBA5551=356782082
UI.SDL_PIXELFORMAT_RGBA8888=373694468
UI.SDL_PIXELFORMAT_RGBX8888=371595268
UI.SDL_PIXELFORMAT_UNKNOWN=0
UI.SDL_PIXELFORMAT_UYVY=1498831189
UI.SDL_PIXELFORMAT_YUY2=844715353
UI.SDL_PIXELFORMAT_YV12=842094169
UI.SDL_PIXELFORMAT_YVYU=1431918169
UI.SDL_PIXELTYPE_ARRAYF16=10
UI.SDL_PIXELTYPE_ARRAYF32=11
UI.SDL_PIXELTYPE_ARRAYU16=8
UI.SDL_PIXELTYPE_ARRAYU32=9
UI.SDL_PIXELTYPE_ARRAYU8=7
UI.SDL_PIXELTYPE_INDEX1=1
UI.SDL_PIXELTYPE_INDEX4=2
UI.SDL_PIXELTYPE_INDEX8=3
UI.SDL_PIXELTYPE_PACKED16=5
UI.SDL_PIXELTYPE_PACKED32=6
UI.SDL_PIXELTYPE_PACKED8=4
UI.SDL_PIXELTYPE_UNKNOWN=0
UI.SDL_POWERSTATE_CHARGED=4
UI.SDL_POWERSTATE_CHARGING=3
UI.SDL_POWERSTATE_NO_BATTERY=2
UI.SDL_POWERSTATE_ON_BATTERY=1
UI.SDL_POWERSTATE_UNKNOWN=0
UI.SDL_POWER_WINDOWS=1
UI.SDL_PREALLOC=1
UI.SDL_PRESSED=1
UI.SDL_QUERY=-1
UI.SDL_QUIT=256
UI.SDL_RELEASED=0
UI.SDL_RENDERER_ACCELERATED=2
UI.SDL_RENDERER_PRESENTVSYNC=4
UI.SDL_RENDERER_SOFTWARE=1
UI.SDL_RENDERER_TARGETTEXTURE=8
UI.SDL_RENDER_TARGETS_RESET=8192
UI.SDL_RLEACCEL=2
UI.SDL_RWOPS_JNIFILE=3
UI.SDL_RWOPS_MEMORY=4
UI.SDL_RWOPS_MEMORY_RO=5
UI.SDL_RWOPS_STDFILE=2
UI.SDL_RWOPS_UNKNOWN=0
UI.SDL_RWOPS_WINFILE=1
UI.SDL_SCANCODE_0=39
UI.SDL_SCANCODE_1=30
UI.SDL_SCANCODE_2=31
UI.SDL_SCANCODE_3=32
UI.SDL_SCANCODE_4=33
UI.SDL_SCANCODE_5=34
UI.SDL_SCANCODE_6=35
UI.SDL_SCANCODE_7=36
UI.SDL_SCANCODE_8=37
UI.SDL_SCANCODE_9=38
UI.SDL_SCANCODE_A=4
UI.SDL_SCANCODE_AC_BACK=270
UI.SDL_SCANCODE_AC_BOOKMARKS=274
UI.SDL_SCANCODE_AC_FORWARD=271
UI.SDL_SCANCODE_AC_HOME=269
UI.SDL_SCANCODE_AC_REFRESH=273
UI.SDL_SCANCODE_AC_SEARCH=268
UI.SDL_SCANCODE_AC_STOP=272
UI.SDL_SCANCODE_AGAIN=121
UI.SDL_SCANCODE_ALTERASE=153
UI.SDL_SCANCODE_APOSTROPHE=52
UI.SDL_SCANCODE_APP1=283
UI.SDL_SCANCODE_APP2=284
UI.SDL_SCANCODE_APPLICATION=101
UI.SDL_SCANCODE_AUDIOMUTE=262
UI.SDL_SCANCODE_AUDIONEXT=258
UI.SDL_SCANCODE_AUDIOPLAY=261
UI.SDL_SCANCODE_AUDIOPREV=259
UI.SDL_SCANCODE_AUDIOSTOP=260
UI.SDL_SCANCODE_B=5
UI.SDL_SCANCODE_BACKSLASH=49
UI.SDL_SCANCODE_BACKSPACE=42
UI.SDL_SCANCODE_BRIGHTNESSDOWN=275
UI.SDL_SCANCODE_BRIGHTNESSUP=276
UI.SDL_SCANCODE_C=6
UI.SDL_SCANCODE_CALCULATOR=266
UI.SDL_SCANCODE_CANCEL=155
UI.SDL_SCANCODE_CAPSLOCK=57
UI.SDL_SCANCODE_CLEAR=156
UI.SDL_SCANCODE_CLEARAGAIN=162
UI.SDL_SCANCODE_COMMA=54
UI.SDL_SCANCODE_COMPUTER=267
UI.SDL_SCANCODE_COPY=124
UI.SDL_SCANCODE_CRSEL=163
UI.SDL_SCANCODE_CURRENCYSUBUNIT=181
UI.SDL_SCANCODE_CURRENCYUNIT=180
UI.SDL_SCANCODE_CUT=123
UI.SDL_SCANCODE_D=7
UI.SDL_SCANCODE_DECIMALSEPARATOR=179
UI.SDL_SCANCODE_DELETE=76
UI.SDL_SCANCODE_DISPLAYSWITCH=277
UI.SDL_SCANCODE_DOWN=81
UI.SDL_SCANCODE_E=8
UI.SDL_SCANCODE_EJECT=281
UI.SDL_SCANCODE_END=77
UI.SDL_SCANCODE_EQUALS=46
UI.SDL_SCANCODE_ESCAPE=41
UI.SDL_SCANCODE_EXECUTE=116
UI.SDL_SCANCODE_EXSEL=164
UI.SDL_SCANCODE_F=9
UI.SDL_SCANCODE_F1=58
UI.SDL_SCANCODE_F10=67
UI.SDL_SCANCODE_F11=68
UI.SDL_SCANCODE_F12=69
UI.SDL_SCANCODE_F13=104
UI.SDL_SCANCODE_F14=105
UI.SDL_SCANCODE_F15=106
UI.SDL_SCANCODE_F16=107
UI.SDL_SCANCODE_F17=108
UI.SDL_SCANCODE_F18=109
UI.SDL_SCANCODE_F19=110
UI.SDL_SCANCODE_F2=59
UI.SDL_SCANCODE_F20=111
UI.SDL_SCANCODE_F21=112
UI.SDL_SCANCODE_F22=113
UI.SDL_SCANCODE_F23=114
UI.SDL_SCANCODE_F24=115
UI.SDL_SCANCODE_F3=60
UI.SDL_SCANCODE_F4=61
UI.SDL_SCANCODE_F5=62
UI.SDL_SCANCODE_F6=63
UI.SDL_SCANCODE_F7=64
UI.SDL_SCANCODE_F8=65
UI.SDL_SCANCODE_F9=66
UI.SDL_SCANCODE_FIND=126
UI.SDL_SCANCODE_G=10
UI.SDL_SCANCODE_GRAVE=53
UI.SDL_SCANCODE_H=11
UI.SDL_SCANCODE_HELP=117
UI.SDL_SCANCODE_HOME=74
UI.SDL_SCANCODE_I=12
UI.SDL_SCANCODE_INSERT=73
UI.SDL_SCANCODE_INTERNATIONAL1=135
UI.SDL_SCANCODE_INTERNATIONAL2=136
UI.SDL_SCANCODE_INTERNATIONAL3=137
UI.SDL_SCANCODE_INTERNATIONAL4=138
UI.SDL_SCANCODE_INTERNATIONAL5=139
UI.SDL_SCANCODE_INTERNATIONAL6=140
UI.SDL_SCANCODE_INTERNATIONAL7=141
UI.SDL_SCANCODE_INTERNATIONAL8=142
UI.SDL_SCANCODE_INTERNATIONAL9=143
UI.SDL_SCANCODE_J=13
UI.SDL_SCANCODE_K=14
UI.SDL_SCANCODE_KBDILLUMDOWN=279
UI.SDL_SCANCODE_KBDILLUMTOGGLE=278
UI.SDL_SCANCODE_KBDILLUMUP=280
UI.SDL_SCANCODE_KP_0=98
UI.SDL_SCANCODE_KP_00=176
UI.SDL_SCANCODE_KP_000=177
UI.SDL_SCANCODE_KP_1=89
UI.SDL_SCANCODE_KP_2=90
UI.SDL_SCANCODE_KP_3=91
UI.SDL_SCANCODE_KP_4=92
UI.SDL_SCANCODE_KP_5=93
UI.SDL_SCANCODE_KP_6=94
UI.SDL_SCANCODE_KP_7=95
UI.SDL_SCANCODE_KP_8=96
UI.SDL_SCANCODE_KP_9=97
UI.SDL_SCANCODE_KP_A=188
UI.SDL_SCANCODE_KP_AMPERSAND=199
UI.SDL_SCANCODE_KP_AT=206
UI.SDL_SCANCODE_KP_B=189
UI.SDL_SCANCODE_KP_BACKSPACE=187
UI.SDL_SCANCODE_KP_BINARY=218
UI.SDL_SCANCODE_KP_C=190
UI.SDL_SCANCODE_KP_CLEAR=216
UI.SDL_SCANCODE_KP_CLEARENTRY=217
UI.SDL_SCANCODE_KP_COLON=203
UI.SDL_SCANCODE_KP_COMMA=133
UI.SDL_SCANCODE_KP_D=191
UI.SDL_SCANCODE_KP_DBLAMPERSAND=200
UI.SDL_SCANCODE_KP_DBLVERTICALBAR=202
UI.SDL_SCANCODE_KP_DECIMAL=220
UI.SDL_SCANCODE_KP_DIVIDE=84
UI.SDL_SCANCODE_KP_E=192
UI.SDL_SCANCODE_KP_ENTER=88
UI.SDL_SCANCODE_KP_EQUALS=103
UI.SDL_SCANCODE_KP_EQUALSAS400=134
UI.SDL_SCANCODE_KP_EXCLAM=207
UI.SDL_SCANCODE_KP_F=193
UI.SDL_SCANCODE_KP_GREATER=198
UI.SDL_SCANCODE_KP_HASH=204
UI.SDL_SCANCODE_KP_HEXADECIMAL=221
UI.SDL_SCANCODE_KP_LEFTBRACE=184
UI.SDL_SCANCODE_KP_LEFTPAREN=182
UI.SDL_SCANCODE_KP_LESS=197
UI.SDL_SCANCODE_KP_MEMADD=211
UI.SDL_SCANCODE_KP_MEMCLEAR=210
UI.SDL_SCANCODE_KP_MEMDIVIDE=214
UI.SDL_SCANCODE_KP_MEMMULTIPLY=213
UI.SDL_SCANCODE_KP_MEMRECALL=209
UI.SDL_SCANCODE_KP_MEMSTORE=208
UI.SDL_SCANCODE_KP_MEMSUBTRACT=212
UI.SDL_SCANCODE_KP_MINUS=86
UI.SDL_SCANCODE_KP_MULTIPLY=85
UI.SDL_SCANCODE_KP_OCTAL=219
UI.SDL_SCANCODE_KP_PERCENT=196
UI.SDL_SCANCODE_KP_PERIOD=99
UI.SDL_SCANCODE_KP_PLUS=87
UI.SDL_SCANCODE_KP_PLUSMINUS=215
UI.SDL_SCANCODE_KP_POWER=195
UI.SDL_SCANCODE_KP_RIGHTBRACE=185
UI.SDL_SCANCODE_KP_RIGHTPAREN=183
UI.SDL_SCANCODE_KP_SPACE=205
UI.SDL_SCANCODE_KP_TAB=186
UI.SDL_SCANCODE_KP_VERTICALBAR=201
UI.SDL_SCANCODE_KP_XOR=194
UI.SDL_SCANCODE_L=15
UI.SDL_SCANCODE_LALT=226
UI.SDL_SCANCODE_LANG1=144
UI.SDL_SCANCODE_LANG2=145
UI.SDL_SCANCODE_LANG3=146
UI.SDL_SCANCODE_LANG4=147
UI.SDL_SCANCODE_LANG5=148
UI.SDL_SCANCODE_LANG6=149
UI.SDL_SCANCODE_LANG7=150
UI.SDL_SCANCODE_LANG8=151
UI.SDL_SCANCODE_LANG9=152
UI.SDL_SCANCODE_LCTRL=224
UI.SDL_SCANCODE_LEFT=80
UI.SDL_SCANCODE_LEFTBRACKET=47
UI.SDL_SCANCODE_LGUI=227
UI.SDL_SCANCODE_LSHIFT=225
UI.SDL_SCANCODE_M=16
UI.SDL_SCANCODE_MAIL=265
UI.SDL_SCANCODE_MEDIASELECT=263
UI.SDL_SCANCODE_MENU=118
UI.SDL_SCANCODE_MINUS=45
UI.SDL_SCANCODE_MODE=257
UI.SDL_SCANCODE_MUTE=127
UI.SDL_SCANCODE_N=17
UI.SDL_SCANCODE_NONUSBACKSLASH=100
UI.SDL_SCANCODE_NONUSHASH=50
UI.SDL_SCANCODE_NUMLOCKCLEAR=83
UI.SDL_SCANCODE_O=18
UI.SDL_SCANCODE_OPER=161
UI.SDL_SCANCODE_OUT=160
UI.SDL_SCANCODE_P=19
UI.SDL_SCANCODE_PAGEDOWN=78
UI.SDL_SCANCODE_PAGEUP=75
UI.SDL_SCANCODE_PASTE=125
UI.SDL_SCANCODE_PAUSE=72
UI.SDL_SCANCODE_PERIOD=55
UI.SDL_SCANCODE_POWER=102
UI.SDL_SCANCODE_PRINTSCREEN=70
UI.SDL_SCANCODE_PRIOR=157
UI.SDL_SCANCODE_Q=20
UI.SDL_SCANCODE_R=21
UI.SDL_SCANCODE_RALT=230
UI.SDL_SCANCODE_RCTRL=228
UI.SDL_SCANCODE_RETURN=40
UI.SDL_SCANCODE_RETURN2=158
UI.SDL_SCANCODE_RGUI=231
UI.SDL_SCANCODE_RIGHT=79
UI.SDL_SCANCODE_RIGHTBRACKET=48
UI.SDL_SCANCODE_RSHIFT=229
UI.SDL_SCANCODE_S=22
UI.SDL_SCANCODE_SCROLLLOCK=71
UI.SDL_SCANCODE_SELECT=119
UI.SDL_SCANCODE_SEMICOLON=51
UI.SDL_SCANCODE_SEPARATOR=159
UI.SDL_SCANCODE_SLASH=56
UI.SDL_SCANCODE_SLEEP=282
UI.SDL_SCANCODE_SPACE=44
UI.SDL_SCANCODE_STOP=120
UI.SDL_SCANCODE_SYSREQ=154
UI.SDL_SCANCODE_T=23
UI.SDL_SCANCODE_TAB=43
UI.SDL_SCANCODE_THOUSANDSSEPARATOR=178
UI.SDL_SCANCODE_U=24
UI.SDL_SCANCODE_UNDO=122
UI.SDL_SCANCODE_UNKNOWN=0
UI.SDL_SCANCODE_UP=82
UI.SDL_SCANCODE_V=25
UI.SDL_SCANCODE_VOLUMEDOWN=129
UI.SDL_SCANCODE_VOLUMEUP=128
UI.SDL_SCANCODE_W=26
UI.SDL_SCANCODE_WWW=264
UI.SDL_SCANCODE_X=27
UI.SDL_SCANCODE_Y=28
UI.SDL_SCANCODE_Z=29
UI.SDL_SWSURFACE=0
UI.SDL_SYSTEM_CURSOR_ARROW=0
UI.SDL_SYSTEM_CURSOR_CROSSHAIR=3
UI.SDL_SYSTEM_CURSOR_HAND=11
UI.SDL_SYSTEM_CURSOR_IBEAM=1
UI.SDL_SYSTEM_CURSOR_NO=10
UI.SDL_SYSTEM_CURSOR_SIZEALL=9
UI.SDL_SYSTEM_CURSOR_SIZENESW=6
UI.SDL_SYSTEM_CURSOR_SIZENS=8
UI.SDL_SYSTEM_CURSOR_SIZENWSE=5
UI.SDL_SYSTEM_CURSOR_SIZEWE=7
UI.SDL_SYSTEM_CURSOR_WAIT=2
UI.SDL_SYSTEM_CURSOR_WAITARROW=4
UI.SDL_SYSWMEVENT=513
UI.SDL_TEXTEDITING=770
UI.SDL_TEXTINPUT=771
UI.SDL_TEXTUREACCESS_STATIC=0
UI.SDL_TEXTUREACCESS_STREAMING=1
UI.SDL_TEXTUREACCESS_TARGET=2
UI.SDL_TEXTUREMODULATE_ALPHA=2
UI.SDL_TEXTUREMODULATE_COLOR=1
UI.SDL_TEXTUREMODULATE_NONE=0
UI.SDL_THREAD_PRIORITY_HIGH=2
UI.SDL_THREAD_PRIORITY_LOW=0
UI.SDL_THREAD_PRIORITY_NORMAL=1
UI.SDL_THREAD_WINDOWS=1
UI.SDL_TIMER_WINDOWS=1
UI.SDL_TRUE=1
UI.SDL_UNSUPPORTED=4
UI.SDL_USEREVENT=32768
UI.SDL_VIDEO_DRIVER_DUMMY=1
UI.SDL_VIDEO_DRIVER_WINDOWS=1
UI.SDL_VIDEO_OPENGL=1
UI.SDL_VIDEO_OPENGL_EGL=1
UI.SDL_VIDEO_OPENGL_ES2=1
UI.SDL_VIDEO_OPENGL_WGL=1
UI.SDL_VIDEO_RENDER_D3D=1
UI.SDL_VIDEO_RENDER_D3D11=0
UI.SDL_VIDEO_RENDER_OGL=1
UI.SDL_VIDEO_RENDER_OGL_ES2=1
UI.SDL_WINDOWEVENT=512
UI.SDL_WINDOWEVENT_CLOSE=14
UI.SDL_WINDOWEVENT_ENTER=10
UI.SDL_WINDOWEVENT_EXPOSED=3
UI.SDL_WINDOWEVENT_FOCUS_GAINED=12
UI.SDL_WINDOWEVENT_FOCUS_LOST=13
UI.SDL_WINDOWEVENT_HIDDEN=2
UI.SDL_WINDOWEVENT_LEAVE=11
UI.SDL_WINDOWEVENT_MAXIMIZED=8
UI.SDL_WINDOWEVENT_MINIMIZED=7
UI.SDL_WINDOWEVENT_MOVED=4
UI.SDL_WINDOWEVENT_NONE=0
UI.SDL_WINDOWEVENT_RESIZED=5
UI.SDL_WINDOWEVENT_RESTORED=9
UI.SDL_WINDOWEVENT_SHOWN=1
UI.SDL_WINDOWEVENT_SIZE_CHANGED=6
UI.SDL_WINDOWPOS_CENTERED=805240832
UI.SDL_WINDOWPOS_CENTERED_MASK=805240832
UI.SDL_WINDOWPOS_UNDEFINED=536805376
UI.SDL_WINDOWPOS_UNDEFINED_MASK=536805376
UI.SDL_WINDOW_ALLOW_HIGHDPI=8192
UI.SDL_WINDOW_BORDERLESS=16
UI.SDL_WINDOW_FOREIGN=2048
UI.SDL_WINDOW_FULLSCREEN=1
UI.SDL_WINDOW_FULLSCREEN_DESKTOP=4097
UI.SDL_WINDOW_HIDDEN=8
UI.SDL_WINDOW_INPUT_FOCUS=512
UI.SDL_WINDOW_INPUT_GRABBED=256
UI.SDL_WINDOW_MAXIMIZED=128
UI.SDL_WINDOW_MINIMIZED=64
UI.SDL_WINDOW_MOUSE_FOCUS=1024
UI.SDL_WINDOW_OPENGL=2
UI.SDL_WINDOW_RESIZABLE=32
UI.SDL_WINDOW_SHOWN=4
//////////////////////////////////////////////////////////////
UI.KMOD_ALT=UI.KMOD_LALT|UI.KMOD_RALT
UI.KMOD_CTRL=UI.KMOD_LCTRL|UI.KMOD_RCTRL
UI.KMOD_SHIFT=UI.KMOD_LSHIFT|UI.KMOD_RSHIFT
UI.KMOD_GUI=UI.KMOD_LGUI|UI.KMOD_RGUI
UI.KMOD_WIN=UI.KMOD_LWIN|UI.KMOD_RWIN
UI["KMOD_⇧"]=UI.KMOD_SHIFT
UI["KMOD_＾"]=UI.KMOD_CTRL
UI["KMOD_⌥"]=UI.KMOD_ALT
UI["KMOD_⌘"]=UI.KMOD_WIN
UI.SDLK_ESC=UI.SDLK_ESCAPE
UI.SDLK_PGDN=UI.SDLK_PAGEDOWN
UI.SDLK_PGUP=UI.SDLK_PAGEUP
UI.SDLK_INS=UI.SDLK_INSERT
UI.SDLK_DEL=UI.SDLK_DELETE

UI.setTimeout=function(f,ms){
	var timer_id;
	timer_id=UI.setInterval(function(){UI.clearInterval(timer_id);f();},ms);
	return timer_id;
};

var g_auto_refresh_timer_id;
var g_need_auto_refresh=0
UI.animation_framerate=60;
var fauto_refresher=function(){
	if(g_need_auto_refresh){
		g_need_auto_refresh=0;
		UI.Refresh()
	}else{
		var my_id=g_auto_refresh_timer_id;
		g_auto_refresh_timer_id=undefined;
		UI.clearInterval(my_id);
	}
}

UI.AutoRefresh=function(){
	if(!UI.is_real){return;}
	if(UI.animation_framerate>20){
		UI.Refresh()
	}else{
		if(g_auto_refresh_timer_id==undefined){
			UI.Refresh()
			g_auto_refresh_timer_id=UI.setInterval(fauto_refresher,1000/UI.animation_framerate)
		}else{
			g_need_auto_refresh=1;
		}
	}
}

UI.SetAnimationFrameRate=function(fps){
	if(g_auto_refresh_timer_id!=undefined){
		var my_id=g_auto_refresh_timer_id;
		g_auto_refresh_timer_id=undefined;
		UI.clearInterval(my_id);
	}
	UI.animation_framerate=fps;
	UI.AutoRefresh();
}

UI.GetPreviousState=function(id){
	var parent=UI.context_parent;
	var attrs_old=parent[id];
	return attrs_old;
};

UI.Keep=function(id,attrs,prototype){
	var tick0=Duktape.__ui_get_tick()//todo
	var parent=UI.context_parent;
	var attrs_old=parent[id];
	var ret;
	////////////////
	var ppt_name=attrs.property_name;
	if(ppt_name){
		var sheet=UI.context_property_sheet;
		if(sheet){
			var ppt=sheet[ppt_name];
			if(Array.isArray(ppt)){
				attrs.value=ppt[0];
				attrs.OnChange=ppt[1];
				if(ppt[2]){attrs.BeginContinuousChange=ppt[2];}
				if(ppt[3]){attrs.EndContinuousChange=ppt[3];}
			}else{
				if(ppt!=undefined){attrs.value=ppt;}
				attrs.OnChange=function(value){sheet[this.property_name]=value;};
			}
		}
	}
	if(attrs_old){
		ret=attrs_old;
		for(var key in attrs){
			var f=attrs[key];
			if(typeof f=='function'){f.prototype=null;}
			ret[key]=f;
		}
		ret.__anchored=0;
	}else{
		if(prototype){
			ret=Object.create(prototype);
			for(var key in attrs){
				var f=attrs[key];
				if(typeof f=='function'){f.prototype=null;}
				ret[key]=f;
			}
		}else{
			ret=attrs;
		}
		ret.__id=id
		parent[id]=ret;
	}
	parent.__children.push(ret)
	if(ret.OnTextInput||ret.OnKeyDown){
		if((!UI.context_tentative_focus||(UI.context_tentative_focus.default_focus||0)<(ret.default_focus||0))){
			UI.context_tentative_focus=ret;
		}
	}
	//parent[id]=attrs;
	UI.style_secs+=Duktape.__ui_seconds_between_ticks(tick0,Duktape.__ui_get_tick())//todo
	return ret;
}

UI.Ditch=function(id){
	var parent=UI.context_parent;
	parent[id]=null;
}

UI.HackCallback=function(f){
	f.prototype=null;
	return f;
}

UI.HackAllCallbacks=function(attrs){
	for(var i in attrs){
		var f=attrs[i];
		if(f&&f.call){f.prototype=null;}
	}
	return attrs;
}

UI.CallIfAvailable=function(parent,id,attrs){
	var cb=parent[id];
	return cb&&cb.call(parent,attrs);
}

UI.core_font_cache={};
UI.font_cache={};
UI.rc={};
UI.Font=function(face,size,embolden){
	//absolute fonts are better for documents anyway
	var pfnt=UI.font_cache[face];
	if(!pfnt){
		var fnames=face.split(",");
		if(fnames.length>0&&fnames[fnames.length-1]=="!"){
			fnames.pop();
		}else{
			fnames=fnames.concat(UI.fallback_font_names);
		}
		pfnt=UI.CreateCoreFontChain(fnames.map(UI.HackCallback(function(cface){
			var pcfnt=UI.core_font_cache[cface];
			if(!pcfnt){
				pcfnt=UI.CreateCoreFontByName(cface);
				UI.core_font_cache[cface]=pcfnt;
			}
			return pcfnt;
		})))
		UI.font_cache[face]=pfnt;
	}
	return UI.CoreFontToFont(pfnt,size,embolden);
}

UI.DiscardCaches=function(){
	UI.core_font_cache={};
	UI.font_cache={};
}

////////////////////////////////////////
UI.Begin=function(obj){
	obj.__parent=UI.context_parent;
	UI.context_parent=obj;
	if(obj.__hwnd){
		obj.__window_parent=UI.context_window;
		UI.context_window=obj;
		UI.context_topmost_callbacks=[];
	}
	if(obj.property_sheet){
		obj.__property_sheet_parent=UI.context_property_sheet;
		UI.context_property_sheet=obj.property_sheet;
	}
	if(obj.__prev_children==undefined){
		obj.__prev_children=(obj.__children||[])
		obj.__children=[]
	}
	return obj;
}

UI.RecordTopMostContext=function(){
	return UI.context_topmost_callbacks.length;
}
UI.FlushTopMostContext=function(n){
	if(n==undefined){n=0}
	for(var i=n;i<UI.context_topmost_callbacks.length;i++){
		UI.context_topmost_callbacks[i]()
	}
	UI.context_topmost_callbacks.length=n;
}

UI.End=function(is_temp){
	var obj=UI.context_parent;
	if(obj.__hwnd){
		//topmost widgets...
		UI.FlushTopMostContext();
		UI.context_topmost_callbacks=undefined
	}
	if(!is_temp){
		var __prev_children=obj.__prev_children;obj.__prev_children=undefined
		var __children=obj.__children;
		//wipe out unneeded children
		for(var i=0;i<__prev_children.length;i++){
			__prev_children[i].__ditch=1
		}
		for(var i=0;i<__children.length;i++){
			__children[i].__ditch=0
		}
		for(var i=0;i<__prev_children.length;i++){
			var c_i=__prev_children[i];
			if(c_i.__ditch&&obj[c_i.__id]==c_i){
				obj[c_i.__id]=undefined
			}
		}
	}
	UI.context_parent=obj.__parent;
	obj.__parent=null;
	if(obj.__hwnd){
		UI.context_window=obj.__window_parent;
		obj.__window_parent=null;
		if(!obj.caret_is_set){
			obj.caret_w=0;
			obj.caret_h=0;
		}
		UI.EndPaint();
	}
	if(obj.property_sheet){
		UI.context_property_sheet=obj.__property_sheet_parent;
	}
	return obj;
}

////////////////////////////////////////
//UI.LayoutText=function(attrs){
//	var font=attrs.font||"Arial,16,b";
//	if(typeof font=='string'){
//		var sparts=font.split(",");
//		if(sparts.length<3){return;}
//		var sbold=sparts.pop();
//		var ssize=sparts.pop();
//		attrs.font=UI.Font(sparts.join(","),parseFloat(ssize),sbold=="b"||sbold=="ab");
//	}
//	UI._LayoutText(attrs);
//}
UI.LayoutText=UI._LayoutText

UI.PushSubWindow=function(x,y,w,h, scale){
	x*=UI.pixels_per_unit
	y*=UI.pixels_per_unit
	w*=UI.pixels_per_unit
	h*=UI.pixels_per_unit
	var prev_subwin=UI.sub_window_stack[UI.sub_window_stack.length-1]
	var x0=prev_subwin[0]+Math.max(0,x)
	var y0=prev_subwin[1]+Math.max(0,y)
	var w0=Math.max(prev_subwin[0]+Math.min(prev_subwin[2],x+w)-x0,0)
	var h0=Math.max(prev_subwin[1]+Math.min(prev_subwin[3],y+h)-y0,0)
	var new_subwin=[x0,y0,w0,h0,prev_subwin[4]*(scale||1)]
	UI.sub_window_stack.push(new_subwin)
	UI._SwitchToSubWindow(new_subwin[0],new_subwin[1],new_subwin[2],new_subwin[3],0,0)
	//todo: clipping-generated translation...
	UI.SetPixelsPerUnit(new_subwin[4])
	UI.pixels_per_unit=new_subwin[4]
	UI.sub_window_offset_x=(new_subwin[0])
	UI.sub_window_offset_y=(new_subwin[1])
	return new_subwin
}

UI.PopSubWindow=function(){
	UI.sub_window_stack.pop()
	var prev_subwin=UI.sub_window_stack[UI.sub_window_stack.length-1]
	UI._SwitchToSubWindow(prev_subwin[0],prev_subwin[1],prev_subwin[2],prev_subwin[3],0,1)
	UI.SetPixelsPerUnit(prev_subwin[4])
	UI.pixels_per_unit=prev_subwin[4]
	UI.sub_window_offset_x=(prev_subwin[0])
	UI.sub_window_offset_y=(prev_subwin[1])
}

lerp=function(a,b,t){return a+(b-a)*t;}
isNumber=function(a){return typeof(a)=='number';}

UI.default_styles={};
UI.curve_linear=function(t){return t}
UI.interpolators={};
UI.default_interpolator=function(a,b,t){
	if(isNumber(a)&&isNumber(b)){
		return lerp(a,b,t);
	}
	return b;
}
UI.lerp_rgba=function(a,b,t){
	return (lerp(a&0xff,b&0xff,t)|0)+(lerp(a&0xff00,b&0xff00,t)&0xff00)+(lerp(a&0xff0000,b&0xff0000,t)&0xff0000)+((lerp((a>>24)&0xff,(b>>24)&0xff,t)|0)<<24)
}
UI.interpolators.color=function(a,b,t){
	if(isNumber(a)&&isNumber(b)){
		//32-bit rgba
		return UI.lerp_rgba(a,b,t);
	}else if(!isNumber(a)&&!isNumber(b)){
		return [
			{x:a[0].x,y:a[0].y,color:UI.lerp_rgba(a[0].color,b[0].color,t)},
			{x:a[1].x,y:a[1].y,color:UI.lerp_rgba(a[1].color,b[1].color,t)}
		];
	}else{
		//coulddo: convert both sides to gradient first, then lerp all attrs, including x/y
	}
	return b;
}
UI.interpolators.caption_color=UI.interpolators.color;
UI.interpolators.border_color=UI.interpolators.color;
UI.interpolators.text_color=UI.interpolators.color;
UI.interpolators.icon_color=UI.interpolators.color;
UI.non_animated_values={
	value:1,
	x:1,
	y:1,
	w:1,
	h:1,
	transition_dt:1}

UI.style_secs=0//todo
UI.style_count=0//todo
UI.StdStyling=function(id,obj,attrs,s_default_style_name,child_style){
	var tick0=Duktape.__ui_get_tick()//todo
	//styling
	var style=obj.style||UI.default_styles[s_default_style_name||"-"];
	if(style){
		//mover / mout / mdown stuff - child styles
		for(var key in style){
			if(key!="$"&&!attrs[key]){
				obj[key]=style[key];
			}
		}
		if(child_style&&style.$){
			var cstyle=style.$[child_style];
			if(cstyle){
				for(var key in cstyle){
					if(!attrs[key]){
						obj[key]=cstyle[key];
					}
				}
			}
		}
	}
	//transition
	if(obj.transition_dt){
		//test whether we need a new transition
		var testTransition=function(){
			if(obj.transition_frame1){
				var dt=obj.transition_dt;
				var fcurve=obj.transition_curve||UI.curve_linear;
				var t=Duktape.__ui_seconds_between_ticks(obj.transition_t0,UI.m_frame_tick)/dt;
				if(!(t>=0&&t<1)){
					//t out of range... assume we reached the goal
					obj.transition_current_frame=obj.transition_frame1;
					obj.transition_frame0=undefined;
					obj.transition_frame1=undefined;
				}else{
					//interpolate the frame
					t=fcurve(t);
					var fc={};
					var f0=obj.transition_frame0;
					var f1=obj.transition_frame1;
					obj.transition_current_frame=fc;
					for(var key in obj.transition_frame0){
						fc[key]=(UI.interpolators[key]||UI.default_interpolator)(f0[key],f1[key],t);
					}
				}
				UI.AutoRefresh();
			}
		}
		testTransition()
		var ref_frame=obj.transition_frame1||obj.transition_current_frame;
		if(!ref_frame){
			ref_frame={};
			for(var key in UI.interpolators){
				if(obj[key]){
					ref_frame[key]=obj[key];
				}
			}
			for(var key in obj){
				if(isNumber(obj[key])&&!UI.non_animated_values[key]){
					ref_frame[key]=obj[key];
				}
			}
			obj.transition_current_frame=ref_frame;
		}else{
			var need_transition=0;
			for(var key in ref_frame){
				if(ref_frame[key]!=obj[key]){
					//gradient comparison
					if((typeof ref_frame[key])=='object'||(typeof obj[key])=='object'){
						continue;
					}
					need_transition=1;
					break
				}
			}
			if(need_transition){
				obj.transition_frame0=obj.transition_current_frame;
				obj.transition_frame1={};
				for(var key in ref_frame){
					obj.transition_frame1[key]=obj[key];
				}
				obj.transition_t0=UI.m_frame_tick;
			}
		}
		////////////////
		//test the running transition
		testTransition()
		if(obj.transition_current_frame){
			var fc=obj.transition_current_frame;
			for(var key in fc){
				obj[key]=fc[key];
			}
		}
	}
	//todo
	UI.style_secs+=Duktape.__ui_seconds_between_ticks(tick0,Duktape.__ui_get_tick())
	UI.style_count++
	//todo
};

UI.doHAlign=function(anchor_align,attrs,obj_anchor){
	if(anchor_align=="left"){
		attrs.x=obj_anchor.x+(attrs.x||0);
	}else if(anchor_align=="center"){
		attrs.x=obj_anchor.x+(attrs.x||0)+(obj_anchor.w-attrs.w)*0.5;
	}else if(anchor_align=="right"){
		attrs.x=obj_anchor.x-(attrs.x||0)+obj_anchor.w-attrs.w;
	}else if(anchor_align=="fill"){
		attrs.w=obj_anchor.w-(attrs.x||0)*2;
		attrs.x=obj_anchor.x+(attrs.x||0);
	}
};

UI.doVAlign=function(anchor_align,attrs,obj_anchor){
	if(anchor_align=="up"){
		attrs.y=obj_anchor.y+(attrs.y||0);
	}else if(anchor_align=="center"){
		attrs.y=obj_anchor.y+(attrs.y||0)+(obj_anchor.h-attrs.h)*0.5;
	}else if(anchor_align=="down"){
		attrs.y=obj_anchor.y-(attrs.y||0)+obj_anchor.h-attrs.h;
	}else if(anchor_align=="fill"){
		attrs.h=obj_anchor.h-(attrs.y||0)*2;
		attrs.y=obj_anchor.y+(attrs.y||0);
	}
};

UI.StdAnchoring=function(id,attrs){
	//anchoring, default to parent
	if(attrs.__anchored){return;}
	var tick0=Duktape.__ui_get_tick()//todo
	var obj_anchor=attrs.anchor;if(obj_anchor=='parent'){obj_anchor=UI.context_parent;}
	var anchor_placement;
	var anchor_align;
	var anchor_valign;
	var anchor_spacing;
	attrs.__anchored=1;
	if(obj_anchor){
		anchor_placement=(attrs.anchor_placement||"inside");
		anchor_align=(attrs.anchor_align||"left");
		anchor_valign=(attrs.anchor_valign||"up");
		anchor_spacing=0;
	}else if(UI.context_parent.layout_direction&&attrs.anchor_placement!='absolute'){
		obj_anchor=UI.context_parent.layout_auto_anchor;
		anchor_placement=(UI.context_parent.layout_direction||"down");
		anchor_align=(UI.context_parent.layout_align||"fill");
		anchor_valign=(UI.context_parent.layout_valign||"fill");
		anchor_spacing=(UI.context_parent.layout_spacing||0);
		if(!obj_anchor){
			obj_anchor={x:UI.context_parent.x,y:UI.context_parent.y,w:UI.context_parent.w,h:UI.context_parent.h};
			if(anchor_placement=="left"){
				obj_anchor.x+=obj_anchor.w;obj_anchor.w=0;
			}else if (anchor_placement=="right"){
				obj_anchor.w=0;
			}else if(anchor_placement=="up"){
				obj_anchor.y+=obj_anchor.h;obj_anchor.h=0;
			}else if(anchor_placement=="down"){
				obj_anchor.h=0;
			}
			obj_anchor.x-=(UI.context_parent.layout_scroll_x||0)
			obj_anchor.y-=(UI.context_parent.layout_scroll_y||0)
		}
	}else{
		//the default handling
		//obj_anchor=UI.context_parent;
		//attrs.x+=obj_anchor.x;
		//attrs.y+=obj_anchor.y;
		return;
	}
	if(anchor_placement=="inside"){
		obj_anchor=(obj_anchor||UI.context_parent);
		UI.doHAlign(anchor_align,attrs,obj_anchor);
		UI.doVAlign(anchor_valign,attrs,obj_anchor);
	}else if(anchor_placement=="up"){
		attrs.y=obj_anchor.y-attrs.h-anchor_spacing-attrs.y;
		UI.doHAlign(anchor_align,attrs,obj_anchor);
	}else if(anchor_placement=="down"){
		attrs.y=obj_anchor.y+obj_anchor.h+anchor_spacing+attrs.y;
		UI.doHAlign(anchor_align,attrs,obj_anchor);
	}else if(anchor_placement=="left"){
		attrs.x=obj_anchor.x-attrs.w-anchor_spacing-attrs.x;
		UI.doVAlign(anchor_valign,attrs,obj_anchor);
	}else if(anchor_placement=="right"){
		attrs.x=obj_anchor.x+obj_anchor.w+anchor_spacing+attrs.x;
		UI.doVAlign(anchor_valign,attrs,obj_anchor);
	}else{
		//bad anchor placement - consider as "absolute"
	}
	if(UI.context_parent.layout_direction&&UI.context_parent.layout_direction!="inside"){
		var layout_auto_anchor={x:attrs.x,y:attrs.y,w:attrs.w,h:attrs.h}
		UI.context_parent.layout_auto_anchor=layout_auto_anchor;
		if(anchor_placement=="left"||anchor_placement=="right"){
			layout_auto_anchor.y=UI.context_parent.y
			layout_auto_anchor.h=UI.context_parent.h
		}else if(anchor_placement=="up"||anchor_placement=="down"){
			layout_auto_anchor.x=UI.context_parent.x
			layout_auto_anchor.w=UI.context_parent.w
		}
	}
	//break the cycle
	attrs.anchor=null;
	UI.style_secs+=Duktape.__ui_seconds_between_ticks(tick0,Duktape.__ui_get_tick())//todo
}

UI.StdWidget=function(id,attrs,style_name,proto){
	var obj=UI.Keep(id,attrs,proto)
	UI.StdStyling(id,obj,attrs,style_name,obj.GetSubStyle?obj.GetSubStyle():undefined)
	UI.StdAnchoring(id,obj)
	return obj;
}
////////////////////////////////////////
UI.DeleteTemps=function(attrs){
	for(var key in attrs){
		//check for leading $
		if(key.charCodeAt(0)==0x24){
			delete attrs[key];
		}
	}
}

////////////////////////////////////////
UI.need_to_refresh=1;
UI.inside_IME=0;
UI.nd_mouse_down=[];
UI.Refresh=function(){
	UI.need_to_refresh=1;
}
UI.InvalidateCurrentFrame=function(){UI.m_frame_is_invalid=1;}

UI.CaptureMouse=function(attrs){
	UI.nd_captured=attrs;
	UI.SDL_SetWindowGrab(attrs.region___hwnd,1);
}

UI.ReleaseMouse=function(attrs){
	if(UI.nd_captured&&UI.nd_captured==attrs){
		UI.nd_captured=null;
		UI.SDL_SetWindowGrab(attrs.region___hwnd,0);
	}
}

UI.SetFocus=function(obj,is_own_call){
	if(UI.nd_focus!=obj){
		var old_focus=UI.nd_focus;
		if(UI.nd_focus){
			UI.CallIfAvailable(UI.nd_focus,"OnBlur",obj)
		}
		UI.nd_focus=obj;
		if(obj){
			UI.CallIfAvailable(obj,"OnFocus",old_focus)
			if(!is_own_call){
				UI.context_focus_is_a_region=1;
			}//if it's set explicitly, assume it's valid for the current frame
		}
	}
	if(obj&&obj.OnTextInput){
		UI.SDL_StartTextInput()
	}else{
		UI.SDL_StopTextInput()
		UI.inside_IME=0
	}
}

UI.HasFocus=function(attrs){
	return UI.nd_focus==attrs;
}

UI.IsKey=function(event,name){
	var mod=event.keymod;
	var sym_tested=0;
	if(typeof name=="string"){name=[name];};
	for(var i=0;i<name.length;i++){
		var name_i=name[i];
		if(event.keysym==UI["SDLK_"+name_i]){sym_tested=1;continue;}
		if(name_i.length==1){
			var asc_code=name_i.charCodeAt(0);
			if(asc_code>=65&&asc_code<=90){asc_code+=32;}
			if(event.keysym==asc_code){sym_tested=1;continue;}
		}
		var mod_mask=UI["KMOD_"+name_i];
		if(mod_mask&&(mod&mod_mask)){
			mod&=~mod_mask;
		}else{
			return 0;
		}
	}
	if(mod!=0){return 0;}
	if(sym_tested){
		return 1;
	}else{
		return undefined;
	}
};

UI.IsModifier=function(event,name){
	return UI.IsKey(event,name)==undefined;
};

var g_re_mac_symbols=new RegExp("[⇧＾⌥⌘]","g")
var g_faddplus=function(smatch){return smatch+"+"}

UI.hotkey_mapping={};
UI.IsHotkey=function(event,hotkey_name){
	var names=UI.hotkey_mapping[hotkey_name];
	if(!names){
		names=hotkey_name.split(" ").map(function(a){return a.replace(g_re_mac_symbols,g_faddplus).split("+")});
		UI.hotkey_mapping[hotkey_name]=names;
	}
	for(var i=0;i<names.length;i++){
		var ret=UI.IsKey(event,names[i]);
		if(ret){return ret;}
	}
	return 0;
};

UI.IsPressed=function(name){
	return UI.SDL_IsPressed(UI["SDL_SCANCODE_"+name])
}

if(!UI.is_real){
	UI.BeginFrame=function(){};
	UI.EndFrame=function(){};
	UI.SDL_StopTextInput=function(){};
	UI.pixels_per_unit=1;//the sandbox shouldn't see or change that
}

UI.frame_callbacks=[];
UI.CallNextFrame=function(f){UI.frame_callbacks.push(f)}
UI.m_frame_tick=Duktape.__ui_get_tick();
UI.DrawFrame=function(){
	//the main painting loop
	UI.need_to_refresh=0;
	UI.BeginFrame();
	UI.m_last_frame_tick=UI.m_frame_tick
	UI.m_frame_tick=Duktape.__ui_get_tick()
	//print("UI.context_focus_is_a_region=0")
	UI.context_focus_is_a_region=0;
	UI.context_paint_queue=[];
	UI.context_hotkeys=[];
	UI.context_regions=[];
	UI.context_parent=UI;
	UI.context_tentative_focus=null;
	var cb0=UI.frame_callbacks
	UI.frame_callbacks=[]
	for(var i=0;i<cb0.length;i++){
		var f=cb0[i]
		f.prototype=null;
		if(f()){
			UI.frame_callbacks.push(f)
		}
	}
	var tick0
	if(UI.enable_timing){
		tick0=Duktape.__ui_get_tick()
		UI.style_secs=0;UI.style_count=0
	}
	UI.__children=[]
	UI.Application("top",{});
	UI.__children=undefined
	if(UI.enable_timing){
		print('JS time=',(Duktape.__ui_seconds_between_ticks(tick0,Duktape.__ui_get_tick())*1000).toFixed(2),'ms')
		print('style time=',(UI.style_secs*1000).toFixed(2),'ms',UI.style_count)
	}
	if(!UI.context_focus_is_a_region){
		//if the node is gone, DO NOT CALL OnBlur! just null it out
		UI.nd_focus=null;
		UI.SDL_StopTextInput()
	}
	if(!UI.nd_focus&&UI.context_tentative_focus){
		UI.SetFocus(UI.context_tentative_focus,1);
		UI.Refresh();
	}
	UI.EndFrame();
	if(UI.enable_timing){
		print('DrawFrame=',(UI.frame_time*1000).toFixed(2),'ms')
		if(!UI.frame_id){UI.frame_id=1}else{UI.frame_id++}
		print('============= Frame #',UI.frame_id)
	}
}

UI.JSDrawWindow=function(obj){
	//var tick0=Duktape.__ui_get_tick()
	UI.GL_Begin(obj.__hwnd)
	UI.Clear(obj.bgcolor||0xffffffff)
	UI.DrawWindow(obj.__hwnd);
	UI.GL_End(obj.__hwnd)
	//print('DrawWindow=',(Duktape.__ui_seconds_between_ticks(tick0,Duktape.__ui_get_tick())*1000).toFixed(2),'ms')
}

UI.GLWidget=function(fcall){
	UI.HackCallback(fcall);
	UI.InsertJSDrawCall(fcall)
}

UI.TopMostWidget=function(fcall){
	UI.HackCallback(fcall);
	UI.context_topmost_callbacks.push(fcall)
}

UI.SetSystemCursor=function(mouse_cursor){
	return UI.SDL_SetSystemCursor(UI["SDL_SYSTEM_CURSOR_"+mouse_cursor.toUpperCase()]||0)
};

UI.OpenFile=function(){};

UI.m_window_map={}
UI.DestroyWindow=function(obj){
	UI.CallIfAvailable(obj,"OnDestroy");
	if(obj.is_main_window){
		UI.SDL_PostQuitEvent();
	}
	UI.m_window_map[obj.__hwnd.toString()]=undefined
	UI.SDL_DestroyWindow(obj.__hwnd)
};

UI.m_poll_jobs=[]
UI.NextTick=function(f){UI.m_poll_jobs.push(UI.HackCallback(f))}
UI.SDL_bad_coordinate_corrector=1;
UI.Run=function(){
	if(!UI.is_real){return;}
	var event=null;
	var t_kill_mousedown=undefined;
	for(;;){
		if(UI.need_to_refresh){
			UI.m_frame_is_invalid=0;
			UI.DrawFrame();
			if(UI.is_real&&UI.GetSRGBStatus().srgb_supported==-1){
				UI.need_to_refresh=1
			}
			if(UI.m_frame_is_invalid){
				continue;
			}
			for(var i=0;i<UI.context_paint_queue.length;i++){
				var obj=UI.context_paint_queue[i];
				obj.caret_state=1;
				UI.JSDrawWindow(obj)
				if(obj.caret_w>0&&obj.caret_h>0&&obj.caret_dt>0){
					if(!obj.has_caret_callback){
						obj.has_caret_callback=1;
						UI.setTimeout((function(obj){var fn_ret=function(){
							if(obj.caret_state>0){
								obj.caret_state--;
							}else{
								obj.caret_state=1;
							}
							UI.JSDrawWindow(obj)
							if(obj.caret_w>0&&obj.caret_h>0&&obj.caret_dt>0){
								obj.has_caret_callback=1;
								UI.setTimeout(fn_ret,obj.caret_dt);
							}else{
								obj.has_caret_callback=0;
							}
						};return fn_ret;})(obj),obj.caret_dt)
					}
				}
			}
			if(UI.Platform.ARCH=="android"&&UI.android_hack_refresh_twice){
				//android bug: need to refresh twice
				UI.android_hack_refresh_twice=0;
				UI.need_to_refresh=1;
			}
		}
		if(UI.need_to_refresh||UI.m_poll_jobs.length){
			var jbs=UI.m_poll_jobs
			UI.m_poll_jobs=[];
			for(var i=0;i<jbs.length;i++){
				jbs[i]();
			}
			event=UI.SDL_PollEvent();
			if(!event){continue;}
		}else{
			event=UI.SDL_WaitEvent();
		}
		while(event){
			if(event.type==UI.SDL_QUIT){return UI;}
			switch(event.type){
			case UI.SDL_USEREVENT:
				if(event.code==1){
					//close
					var obj=UI.m_window_map[event.windowID.toString()]
					if(obj){
						if(!UI.CallIfAvailable(obj,"OnClose")){
							UI.DestroyWindow(obj)
						}
					}
					break;
				}
				if(event.code==2){
					//timer
					var fn=UI.getTimerFunction(event.data1);
					if(fn){fn();}
				}
				break
			case UI.SDL_WINDOWEVENT:
				switch(event.event){
				case UI.SDL_WINDOWEVENT_SIZE_CHANGED:
					if(UI.Platform.ARCH=="android"){
						//android bug: need to refresh twice
						UI.android_hack_refresh_twice=1;
					}
					UI.Refresh();
					break
				case UI.SDL_WINDOWEVENT_RESIZED:
					UI.Refresh();
					break
				case UI.SDL_WINDOWEVENT_SHOWN:
				case UI.SDL_WINDOWEVENT_EXPOSED:
					var obj=UI.m_window_map[event.windowID.toString()];
					if(obj){
						UI.JSDrawWindow(obj)
					}
					break;
				case UI.SDL_WINDOWEVENT_ENTER:
					t_kill_mousedown=event.timestamp;
					break;
				case UI.SDL_WINDOWEVENT_FOCUS_GAINED:
					var obj_window=UI.m_window_map[event.windowID.toString()];
					obj.m_window_has_focus=1
					break;
				case UI.SDL_WINDOWEVENT_FOCUS_LOST:
					var obj_window=UI.m_window_map[event.windowID.toString()];
					if(obj_window.OnWindowBlur){obj_window.OnWindowBlur()};
					obj.m_window_has_focus=0
					UI.SetFocus(null)
					break;
				}
				break
			case UI.SDL_KEYDOWN:
			case UI.SDL_KEYUP:
				if(UI.inside_IME){break;}
				var obj_window=UI.m_window_map[event.windowID.toString()];
				event.keymod&=~(UI.KMOD_CAPS|UI.KMOD_NUM)//get rid of the bogus SDL flags
				if(obj_window){
					if(event.keysym==UI.SDLK_LALT||event.keysym==UI.SDLK_RALT){
						//alt-menu case
						//print("ALT",event.type==UI.SDL_KEYDOWN?"DOWN":"UP")
						if(event.type==UI.SDL_KEYDOWN){
							obj_window.m_just_alted=1;
						}else{
							if(obj_window.m_just_alted){
								if(obj_window.OnMenu){
									obj_window.OnMenu();
								}
							}
							obj_window.m_just_alted=0;
						}
					}else{
						obj_window.m_just_alted=0;
					}
				}
				if(event.type==UI.SDL_KEYDOWN){
					var hotkeys=UI.context_hotkeys;
					var lg=hotkeys.length;
					var hotkeyed=0;
					for(var i=lg-1;i>=0;i--){
						var attrs=hotkeys[i];
						if(attrs.key&&UI.IsHotkey(event,attrs.key)){
							attrs.action();
							hotkeyed=1
							break;
						}
					}
					if(hotkeyed){break;}
				}
				//keyboard focus
				if(UI.nd_focus){
					UI.CallIfAvailable(UI.nd_focus,event.type==UI.SDL_KEYDOWN?"OnKeyDown":"OnKeyUp",event);
				}
				break
			case UI.SDL_TEXTEDITING:
				if(UI.nd_focus){
					UI.CallIfAvailable(UI.nd_focus,"OnTextEdit",event);
				}
				UI.inside_IME=(event.text.length>0)
				break
			case UI.SDL_TEXTINPUT:
				var hotkeys=UI.context_hotkeys;
				var lg=hotkeys.length;
				var hotkeyed=0;
				for(var i=lg-1;i>=0;i--){
					var attrs=hotkeys[i];
					if(attrs.text&&event.text==attrs.text){
						attrs.action();
						hotkeyed=1
						break;
					}
				}
				if(hotkeyed){break;}
				////////
				if(UI.nd_focus){
					UI.CallIfAvailable(UI.nd_focus,"OnTextInput",event);
				}
				UI.inside_IME=0
				break
			case UI.SDL_MOUSEWHEEL:
				if(UI.nd_focus){
					UI.CallIfAvailable(UI.nd_focus,"OnMouseWheel",event);
				}
				break
			//UI.nd_mouse_over, UI.nd_key_focus, UI.nd_captured
			case UI.SDL_MOUSEMOTION:
			case UI.SDL_MOUSEBUTTONDOWN:
			case UI.SDL_MOUSEBUTTONUP:
				event.x*=UI.SDL_bad_coordinate_corrector
				event.y*=UI.SDL_bad_coordinate_corrector
				if(t_kill_mousedown==event.timestamp&&event.type==UI.SDL_MOUSEBUTTONDOWN){
					//filter out the bogus mousedowns sent by SDL
					break
				}
				var regions=UI.context_regions;
				var lg=regions.length;
				var nd_mouse_receiver=null;
				var mouse_cursor="arrow";
				//print("------------------")
				//for(var i=lg-1;i>=0;i--){
				//	var attrs=regions[i];
				//	var dx=event.x-attrs.x;
				//	var dy=event.y-attrs.y;
				//	var is_hit=0
				//	if(dx>=0&&dx<attrs.w&&dy>=0&&dy<attrs.h){
				//		is_hit=1;
				//	}
				//	print(attrs.x,attrs.y,attrs.w,attrs.h,is_hit?"hit":"")
				//}
				if(!UI.nd_captured){
					for(var i=lg-1;i>=0;i--){
						var attrs=regions[i];
						var dx=(event.x-attrs.sub_window_offset_x)/attrs.sub_window_scale-attrs.x;
						var dy=(event.y-attrs.sub_window_offset_y)/attrs.sub_window_scale-attrs.y;
						//print(attrs.sub_window_scale,dx,dy,attrs.sub_window_offset_x,attrs.sub_window_offset_y,attrs.x,attrs.y)
						if(dx>=0&&dx<attrs.w&&dy>=0&&dy<attrs.h){
							nd_mouse_receiver=attrs;
							break;
						}
					}
				}else{
					nd_mouse_receiver=UI.nd_captured;
				}
				if(!nd_mouse_receiver){
					if(event.type==UI.SDL_MOUSEMOTION){
						if(UI.nd_mouse_over){
							var xbk=event.x,ybk=event.y;
							event.x-=UI.nd_mouse_over.sub_window_offset_x;
							event.y-=UI.nd_mouse_over.sub_window_offset_y;
							event.x/=UI.nd_mouse_over.sub_window_scale
							event.y/=UI.nd_mouse_over.sub_window_scale
							UI.CallIfAvailable(UI.nd_mouse_over,"OnMouseOut",event);
							event.x=xbk;event.y=ybk;
							UI.nd_mouse_over=null;
						}
					}
					UI.SetSystemCursor(mouse_cursor)
					break;
				}else{
					mouse_cursor=(nd_mouse_receiver.mouse_cursor||mouse_cursor);
					UI.SetSystemCursor(mouse_cursor)
				}
				var event_x0=event.x,event_y0=event.y
				event.x-=nd_mouse_receiver.sub_window_offset_x;
				event.y-=nd_mouse_receiver.sub_window_offset_y;
				event.x/=nd_mouse_receiver.sub_window_scale
				event.y/=nd_mouse_receiver.sub_window_scale
				if(event.type==UI.SDL_MOUSEMOTION){
					//nd_mouse_receiver
					if(!UI.nd_mouse_over||UI.nd_mouse_over!=nd_mouse_receiver){
						if(UI.nd_mouse_over){
							var xbk=event.x,ybk=event.y;
							event.x=(event_x0-UI.nd_mouse_over.sub_window_offset_x)/UI.nd_mouse_over.sub_window_scale;
							event.y=(event_y0-UI.nd_mouse_over.sub_window_offset_y)/UI.nd_mouse_over.sub_window_scale;
							UI.CallIfAvailable(UI.nd_mouse_over,"OnMouseOut",event);
							event.x=xbk;event.y=ybk;
						}
						UI.nd_mouse_over=nd_mouse_receiver;
						UI.CallIfAvailable(nd_mouse_receiver,"OnMouseOver",event);
					}
					UI.CallIfAvailable(nd_mouse_receiver,"OnMouseMove",event);
				}else{
					//do dragging in a higher level abstraction
					if(event.type==UI.SDL_MOUSEBUTTONDOWN){
						UI.nd_mouse_down[event.button]=nd_mouse_receiver;
						UI.CallIfAvailable(nd_mouse_receiver,"OnMouseDown",event);
					}else{
						var attrs_previous=UI.nd_mouse_down[event.button];
						UI.CallIfAvailable(nd_mouse_receiver,"OnMouseUp",event);
						if(attrs_previous&&attrs_previous==nd_mouse_receiver){
							UI.CallIfAvailable(nd_mouse_receiver,"OnClick",event);
						}
						UI.nd_mouse_down[event.button]=null;
					}
				}
				break;
			case UI.SDL_DROPFILE:
				UI.OpenFile(event.file)
				break
			}
			event=UI.SDL_PollEvent();
			if(!event)break;
		}
	}
	UI.SDL_Quit()
	return UI;
}

if(UI.Platform.ARCH=="android"){
	print=function(){
		Duktape.__write_log(Array.prototype.slice.call(arguments,0).join(" "))
	}
}

UI.InheritClass=function(proto0,proto1){
	Object.setPrototypeOf(proto1,proto0)
	return proto1
}

UI.m_translation={}
UI._=function(s){
	return UI.m_translation[s]||s;
}
var g_regex_format=new RegExp("@([0-9]+)","g")
UI.Format=function(s){
	var args0=arguments
	return UI._(s).replace(g_regex_format,function(smatch,sid){
		var value=args0[sid];
		if(!value){
			throw new Error("insufficient number of parameters")
		}
		return value;
	});
}

//to translate it, overload the function, not the names array
var g_english_month_names=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
UI.MonthDay=function(month,day){
	return g_english_month_names[month]+" "+(day+1).toString()
}

UI.m_mac_key_names={
	"SHIFT":"\u21E7",
	"CTRL":"\uFF3E",
	"ALT":"\u2325",
	"WIN":"\u2318",
};
UI.LocalizeKeyName=function(s){
	if(UI.IS_APPLE){
		return s.split("+").map(function(a){return UI.m_mac_key_names[a]||a}).join("");
	}else{
		return s;
	}
}

UI.DumpCallStack=function(){
	try{
		throw new Error("call stack")
	}catch(error){
		print(error.stack)
	}
}
